### ISSUE TITLE
embed Biolink model in application

### ISSUE THREAD

**Issue by balhoff** [NCATS-Tangerine/cam-kp-api#262]
We should embed the biolink-model.yaml and context.jsonld files in the resources folder, so that we can migrate to new versions more predictably. Then coordinate changes to these with the version included in the database.

**Comment by balhoff** [comment]
@jdr0887 this is meant to be essentially what we talked about this morning.

**Comment by jdr0887** [comment]
I have this fixed in trapi-1.1.  

To be more explicit...we are downloading both the biolink-model.yaml & the context.jsonld file to src/main/resources.  From there, a test case will parse those files & serialize a BiolinkData case class to json that has the merged prefixes integrated.  Only that biolink-data.json file is deserialized on server startup/init.
